# Generated by Django 5.0.7 on 2024-07-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professor', '0002_alter_professor_user'),
        ('Students', '0013_remove_events_students_remove_modules_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(related_name='events', to='Students.students')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Duration', models.IntegerField()),
                ('Credit', models.IntegerField()),
                ('Professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Professor.professor')),
                ('Students', models.ManyToManyField(blank=True, related_name='modules', to='Students.students')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Link', models.FileField(upload_to='Documents/')),
                ('Modules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='Commun.modules')),
            ],
        ),
    ]
