# Generated by Django 5.0.7 on 2024-08-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professor', '0001_initial'),
        ('Students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(related_name='events', to='Students.students')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thème', to='Commun.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Professor.professor')),
                ('students', models.ManyToManyField(blank=True, related_name='modules', to='Students.students')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='modules',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='Commun.modules'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.FileField(upload_to='Documents/')),
                ('modules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='Commun.modules')),
            ],
        ),
    ]
