# Generated by Django 5.0.7 on 2024-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Pseudo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
