# Generated by Django 5.0.7 on 2024-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Students',
            field=models.ManyToManyField(blank=True, null=True, to='Students.students'),
        ),
    ]
