# Generated by Django 5.0.7 on 2024-07-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Students',
            field=models.ManyToManyField(blank=True, to='Students.students'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Inscription',
            field=models.DateField(auto_now_add=True),
        ),
    ]
