# Generated by Django 5.0.7 on 2024-07-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_alter_course_students_alter_students_inscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Bith',
            new_name='Birth',
        ),
    ]
