# Generated by Django 5.0.7 on 2024-07-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_alter_course_name_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='link',
            new_name='Link',
        ),
    ]
