# Generated by Django 5.0.7 on 2024-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0008_rename_link_documents_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Link',
            field=models.FileField(upload_to='Documents/'),
        ),
    ]
