# Generated by Django 5.0.7 on 2024-07-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0001_initial'),
        ('Students', '0011_alter_students_user_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='Professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Professor.professor'),
        ),
    ]
