# Generated by Django 5.0.7 on 2024-07-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0012_modules_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='students',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='Professor',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='Students',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
